name: Build and Deploy to ACR

on:
  push:
    branches:
      - main

env:
  ACR_NAME: jubbuseacrinmh    # without .azurecr.io
  IMAGE_NAME: myecomapp

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Build Docker Image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}

      # Upload image_name.txt as artifact
      - name: Upload image_name.txt as artifact
        uses: actions/upload-artifact@v2
        with:
          name: image-name
          path: image_name.txt

      # Download image_name.txt from artifact
      - name: Download image_name.txt artifact
        uses: actions/download-artifact@v2
        with:
          name: image-name
          path: ./artifacts

      # Read Image Name from artifact
      - name: Read Image Name from artifact
        run: |
          IMAGE_NAME=$(cat ./artifacts/image_name.txt)
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV